// aula4/portal-produtos/src/pages/listarprodutos/ProductCard.tsx

import './css/ProductCard.css'
import type {ProductResponse} from "../../dtos/ProductResponse.ts";
import type {ComponentType} from "react";

interface Props {
    product: ProductResponse
}

const ProductCard: ComponentType<Props> = ({ product }) => {
    return (
        <article className="product-card">
            <img
                className="product-card__image"
                src={product.pictureUrl}
                alt={product.name}
            />

            <div className="product-card__body">
                <h2 className="product-card__title">id: {product.id}</h2>
                <h2 className="product-card__title">{product.name}</h2>
                <p className="product-card__price">
                    R$ {product.price.toFixed(2).replace('.', ',')}
                </p>
                <p className="product-card__category">{product.category}</p>
                {/* opcional: descrição resumida */}
                <p className="product-card__description">
                    {product.description.slice(0, 100)}…
                </p>
            </div>
        </article>
    )
}

export default ProductCard

// projeto-final/portal-produtos-angular/src/component/product-card/product-card.component.ts
import {Component, Input} from '@angular/core';
import {ProductResponse} from '../../models/product-response.model';

@Component({
  selector: 'app-product-card',
  imports: [],
  templateUrl: './product-card.component.html',
  styleUrl: './product-card.component.css'
})
export class ProductCardComponent {

  @Input() product!: ProductResponse;
}

<img src="{{product.pictureUrl}}">
<h3>{{product.id}}</h3>
<p>{{product.name}}</p>
<p>{{product.price}}</p>
<p>{{product.category}}</p>
<p>{{product.description}}</p>
